<?php

namespace sfdBundle\Repository;

/**
 * jobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class jobRepository extends \Doctrine\ORM\EntityRepository
{
}
