<?php

namespace sfdBundle\Repository;

/**
 * newRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class newRepository extends \Doctrine\ORM\EntityRepository
{
}
