<?php

namespace sfdBundle\Repository;

/**
 * reclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reclamationRepository extends \Doctrine\ORM\EntityRepository
{
}
