<?php

namespace sfdBundle\Repository;

/**
 * requestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class requestRepository extends \Doctrine\ORM\EntityRepository
{
}
