<?php

namespace sfdBundle\Repository;

/**
 * sondageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sondageRepository extends \Doctrine\ORM\EntityRepository
{
}
